const DEMO_STOCKS=[
{name:"Reliance Industries",symbol:"RELIANCE",price:1428.50,change:1.24,cap:"Large Cap",sector:"Energy",pe:23.8,roe:9.7,revenue:"₹10.8L Cr",profit:"₹81,309 Cr",debt:"₹3.47L Cr",promoter:"50.1%",desc:"Diversified Indian conglomerate with businesses across energy, retail and digital services."},
{name:"HDFC Bank",symbol:"HDFCBANK",price:1018.40,change:-0.46,cap:"Large Cap",sector:"Banking",pe:19.4,roe:16.2,revenue:"₹2.9L Cr",profit:"₹67,347 Cr",debt:"—",promoter:"0%",desc:"One of India's largest private-sector banks."},
{name:"ICICI Bank",symbol:"ICICIBANK",price:1455.20,change:.88,cap:"Large Cap",sector:"Banking",pe:18.7,roe:17.1,revenue:"₹2.4L Cr",profit:"₹47,227 Cr",debt:"—",promoter:"0%",desc:"Major Indian private-sector bank serving retail and corporate customers."},
{name:"Infosys",symbol:"INFY",price:1512.70,change:1.63,cap:"Large Cap",sector:"IT",pe:24.1,roe:30.4,revenue:"₹1.62L Cr",profit:"₹26,713 Cr",debt:"₹9,900 Cr",promoter:"14.6%",desc:"Global IT services and consulting company."},
{name:"Tata Motors",symbol:"TATAMOTORS",price:692.15,change:-1.14,cap:"Large Cap",sector:"Auto",pe:9.8,roe:21.5,revenue:"₹4.45L Cr",profit:"₹27,149 Cr",debt:"₹1.1L Cr",promoter:"42.6%",desc:"Automotive company with passenger, commercial and luxury vehicle businesses."},
{name:"Federal Bank",symbol:"FEDERALBNK",price:205.60,change:.74,cap:"Mid Cap",sector:"Banking",pe:9.9,roe:13.7,revenue:"₹28,900 Cr",profit:"₹4,200 Cr",debt:"—",promoter:"0%",desc:"Indian private-sector commercial bank."},
{name:"Indian Hotels",symbol:"INDHOTEL",price:763.80,change:1.17,cap:"Mid Cap",sector:"Hotels",pe:38.4,roe:10.8,revenue:"₹8,500 Cr",profit:"₹1,900 Cr",debt:"₹5,100 Cr",promoter:"38.2%",desc:"Hospitality company behind the Taj brand."},
{name:"BSE Ltd",symbol:"BSE",price:2584.10,change:3.12,cap:"Mid Cap",sector:"Financial",pe:45.6,roe:22.6,revenue:"₹3,000 Cr",profit:"₹1,100 Cr",debt:"Low",promoter:"0%",desc:"Operator of India's oldest stock exchange."},
{name:"Zen Technologies",symbol:"ZENTEC",price:1542.70,change:2.86,cap:"Small Cap",sector:"Defence",pe:63.1,roe:19.8,revenue:"₹900 Cr",profit:"₹200 Cr",debt:"Low",promoter:"55%",desc:"Defence training and anti-drone technology company."},
{name:"RITES",symbol:"RITES",price:272.40,change:-1.35,cap:"Small Cap",sector:"Railways",pe:18.3,roe:14.4,revenue:"₹3,000 Cr",profit:"₹500 Cr",debt:"Low",promoter:"72%",desc:"Transport infrastructure consultancy and engineering company."}
];

const BASE_NEWS=[
{title:"Indian equities remain in focus as investors track global cues",tag:"MARKETS",time:"Today • 10:20 AM",body:"Markets are responding to global risk sentiment, institutional flows and domestic developments. Replace this demo story with your original editorial summary."},
{title:"Companies to watch: results, dividends and corporate actions",tag:"CORPORATE",time:"Today • 09:35 AM",body:"Results, dividends, bonus issues, splits and other corporate disclosures can create stock-specific catalysts."},
{title:"Nifty 50 stocks: key themes traders are watching",tag:"NIFTY",time:"Today • 08:50 AM",body:"Index direction, sector rotation, volume and company-specific news are among the factors traders commonly monitor."},
{title:"IPO calendar: track upcoming public issues",tag:"IPO",time:"Yesterday • 06:10 PM",body:"Track IPO openings, price bands, subscription information and listing updates."}
];

function getNews(){return JSON.parse(localStorage.getItem("stocknews_news")||"null")||BASE_NEWS}
function saveNews(n){localStorage.setItem("stocknews_news",JSON.stringify(n))}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function stock(sym){return DEMO_STOCKS.find(s=>s.symbol.toLowerCase()===sym.toLowerCase())}
function layout(html){document.getElementById("app").innerHTML=html;window.scrollTo(0,0)}
function home(){
 const ms=DEMO_STOCKS.slice(0,4), n=getNews();
 layout(`<section class="container hero"><div><span class="eyebrow">INDIAN STOCK MARKET</span><h1>Market news.<br><span>Stock insights.</span></h1><p>StockNews brings market news, stock discovery, screening and individual stock pages together in one simple portal.</p><div class="actions"><a class="btn primary" href="#/news">Latest News</a><a class="btn secondary" href="#/screener">Stock Screener</a></div></div><div class="hero-card"><span class="eyebrow">STOCKNEWS V2</span><h2 style="color:white">Your market dashboard</h2><p style="font-size:14px">Admin panel included. Add your own news and manage it from this browser.</p><div class="mini-grid">${ms.map(m=>`<div class="mini"><small>${m.symbol}</small><b>₹${m.price.toLocaleString("en-IN")}</b><span class="${m.change>=0?"up":"down"}">${m.change>=0?"+":""}${m.change}%</span></div>`).join("")}</div></div></section>
 <section class="container section"><div class="head"><div><span class="eyebrow">MARKET</span><h2>Market Overview</h2></div></div><div class="market-grid">${ms.map(m=>`<div class="card market-card"><span class="muted">${m.name}</span><h3>₹${m.price.toLocaleString("en-IN")}</h3><b class="${m.change>=0?"up":"down"}">${m.change>=0?"+":""}${m.change}%</b></div>`).join("")}</div></section>
 <section class="container section"><div class="head"><div><span class="eyebrow">LATEST</span><h2>Latest News</h2></div><a class="btn secondary" href="#/news">All News →</a></div><div class="news-grid"><article class="card featured"><span class="tag">${esc(n[0].tag)}</span><h2>${esc(n[0].title)}</h2><p class="muted">${esc(n[0].body)}</p><span class="meta">${esc(n[0].time)}</span></article><div class="card">${n.slice(1,4).map((x,i)=>`<div class="news-item" onclick="openNews(${i+1})"><span class="tag">${esc(x.tag)}</span><h3>${esc(x.title)}</h3><span class="meta">${esc(x.time)}</span></div>`).join("")}</div></div></section>
 <section class="container section"><div class="head"><div><span class="eyebrow">EXPLORE</span><h2>Stock Categories</h2></div></div><div class="section-grid">${[["Large Cap","Established market leaders","Large Cap"],["Mid Cap","Growing listed companies","Mid Cap"],["Small Cap","Smaller listed businesses","Small Cap"],["Top Gainers","Positive price moves","up"],["Top Losers","Stocks under pressure","down"],["Stock Screener","Find stocks by filters","screener"]].map(x=>`<a class="card category" href="${x[2]==="screener"?"#/screener":"#/screener?cap="+encodeURIComponent(x[2])}"><b>${x[0]}</b><span>${x[1]}</span><strong>→</strong></a>`).join("")}</div></section>`);
}
function newsPage(){
 const n=getNews();layout(`<section class="container section"><span class="eyebrow">STOCKNEWS</span><h1 style="font-size:48px;letter-spacing:-2px">Latest Market News</h1><div class="section-grid">${n.map((x,i)=>`<article class="card news-item" onclick="openNews(${i})"><span class="tag">${esc(x.tag)}</span><h2>${esc(x.title)}</h2><p class="muted">${esc(x.body)}</p><span class="meta">${esc(x.time)}</span></article>`).join("")}</div></section>`)
}
function openNews(i){const n=getNews()[i];layout(`<section class="container section"><a href="#/news" class="muted">← Back to News</a><article class="card" style="margin-top:18px;max-width:850px"><span class="tag">${esc(n.tag)}</span><h1 style="font-size:46px;letter-spacing:-2px">${esc(n.title)}</h1><span class="meta">${esc(n.time)}</span><p style="font-size:17px;line-height:1.9;color:#475467;margin-top:25px">${esc(n.body)}</p><div class="card" style="margin-top:30px;background:#f8fafc"><b>Editorial note</b><p class="muted">Replace demo text with your own original reporting/summary. Do not republish complete third-party articles without permission.</p></div></article></section>`)}
function screener(){
 let q="",cap="all",sector="all",trend="all"; const sectors=[...new Set(DEMO_STOCKS.map(s=>s.sector))].sort();
 function render(){const arr=DEMO_STOCKS.filter(s=>(!q||(s.name+" "+s.symbol).toLowerCase().includes(q))&&(cap==="all"||s.cap===cap)&&(sector==="all"||s.sector===sector)&&(trend==="all"||(trend==="up"?s.change>0:s.change<0)));document.getElementById("stockRows").innerHTML=arr.map(s=>`<tr><td><a class="company" href="#/stock/${s.symbol}">${s.name}</a><span class="symbol">${s.symbol}</span></td><td>₹${s.price.toLocaleString("en-IN",{minimumFractionDigits:2})}</td><td class="${s.change>=0?"up":"down"}">${s.change>=0?"+":""}${s.change.toFixed(2)}%</td><td>${s.cap}</td><td>${s.sector}</td><td>${s.pe}</td><td>${s.roe}%</td></tr>`).join("")||`<tr><td colspan="7">No stocks found.</td></tr>`}
 layout(`<section class="container section"><span class="eyebrow">DISCOVER</span><h1 style="font-size:48px;letter-spacing:-2px">Stock Screener</h1><div class="filters"><input id="q" class="input" placeholder="Search company or symbol"><select id="cap" class="select"><option value="all">All Market Caps</option><option>Large Cap</option><option>Mid Cap</option><option>Small Cap</option></select><select id="sector" class="select"><option value="all">All Sectors</option>${sectors.map(x=>`<option>${x}</option>`).join("")}</select><select id="trend" class="select"><option value="all">All Trends</option><option value="up">Gainers</option><option value="down">Losers</option></select></div><div class="table-wrap"><table><thead><tr><th>Company</th><th>Price</th><th>Change</th><th>Cap</th><th>Sector</th><th>P/E</th><th>ROE</th></tr></thead><tbody id="stockRows"></tbody></table></div></section>`);
 ["q","cap","sector","trend"].forEach(id=>document.getElementById(id).oninput=()=>{q=document.getElementById("q").value.toLowerCase();cap=document.getElementById("cap").value;sector=document.getElementById("sector").value;trend=document.getElementById("trend").value;render()}); render();
}
function stockPage(sym){
 const s=stock(sym); if(!s){layout(`<section class="container section"><h2>Stock not found</h2><a href="#/screener">Back to Screener</a></section>`);return}
 const related=getNews().filter(n=>n.title.toLowerCase().includes(s.symbol.toLowerCase())||n.tag==="CORPORATE").slice(0,3);
 layout(`<section class="container stock-hero"><a class="muted" href="#/screener">← Back to Screener</a><div class="stock-title"><div><span class="eyebrow">${s.cap.toUpperCase()} • ${s.sector.toUpperCase()}</span><h1 style="font-size:48px;letter-spacing:-2px;margin-bottom:5px">${s.name}</h1><span class="muted">${s.symbol} • Demo data</span></div><div><div class="price">₹${s.price.toLocaleString("en-IN",{minimumFractionDigits:2})}</div><b class="${s.change>=0?"up":"down"}">${s.change>=0?"+":""}${s.change}%</b></div></div><div class="stats">${[["Market Cap",s.cap],["P/E",s.pe],["ROE",s.roe+"%"],["Promoter",s.promoter]].map(x=>`<div class="card stat"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div></section>
<section class="container section stock-columns"><div><div class="card"><h2>Price Chart</h2><div class="chart">Chart area — connect live historical data API in the next version</div></div><div class="card" style="margin-top:15px"><h2>About ${s.name}</h2><p class="muted" style="line-height:1.8">${esc(s.desc)}</p></div></div><aside><div class="card"><h2>Key Financials</h2>${[["Revenue",s.revenue],["Profit",s.profit],["Debt",s.debt],["P/E",s.pe],["ROE",s.roe+"%"]].map(x=>`<p style="display:flex;justify-content:space-between;border-bottom:1px solid var(--line);padding:10px 0;margin:0"><span class="muted">${x[0]}</span><b>${x[1]}</b></p>`).join("")}</div><div class="card" style="margin-top:15px"><h2>Related News</h2>${related.length?related.map(n=>`<div class="news-item"><b>${esc(n.title)}</b><div class="meta">${esc(n.time)}</div></div>`).join(""):"<p class='muted'>No related news yet.</p>"}</div></aside></section>`);
}
function admin(){
 const n=getNews();
 layout(`<section class="container section"><span class="eyebrow">ADMIN PANEL</span><h1 style="font-size:48px;letter-spacing:-2px">Manage StockNews</h1><p class="muted">यह simple browser-based admin panel है। अभी posts आपके इसी browser के local storage में save होते हैं.</p><div class="admin-grid"><div class="card"><h2>Add News</h2><form id="newsForm" class="form"><input id="ntitle" class="input" required placeholder="News headline"><input id="ntag" class="input" required placeholder="Category e.g. MARKETS"><input id="ntime" class="input" placeholder="Time e.g. Today • 10:30 AM"><textarea id="nbody" class="textarea" required placeholder="Write your original news summary..."></textarea><button class="btn primary">Publish News</button></form></div><div class="card"><h2>Admin Features</h2><p class="muted">✓ Add news<br>✓ Delete news<br>✓ News instantly appears on Home/News<br>✓ Data remains after browser refresh</p><button class="btn danger" id="resetNews">Reset Demo News</button><p class="meta" style="margin-top:15px">For a real public website, we should add a secure backend/login before allowing multiple users to manage content.</p></div></div><div class="card" style="margin-top:15px"><h2>Published News</h2><div id="adminNews" class="news-admin">${n.map((x,i)=>`<div class="admin-news"><div><span class="tag">${esc(x.tag)}</span><b>${esc(x.title)}</b><div class="meta">${esc(x.time)}</div></div><button class="btn danger" onclick="deleteNews(${i})">Delete</button></div>`).join("")}</div></div></section>`);
 document.getElementById("newsForm").onsubmit=e=>{e.preventDefault();const arr=getNews();arr.unshift({title:ntitle.value,tag:ntag.value.toUpperCase(),time:ntime.value||"Just now",body:nbody.value});saveNews(arr);toast("News published successfully");admin()};
 document.getElementById("resetNews").onclick=()=>{if(confirm("Reset demo news?")){localStorage.removeItem("stocknews_news");admin();toast("Demo news restored")}};
}
function deleteNews(i){const n=getNews();n.splice(i,1);saveNews(n);admin();toast("News deleted")}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2200)}
function route(){const h=location.hash||"#/";const p=h.slice(2).split("?")[0];if(p==="")home();else if(p==="news")newsPage();else if(p==="screener")screener();else if(p==="admin")admin();else if(p.startsWith("stock/"))stockPage(p.split("/")[1]);else home()}
document.getElementById("menu").onclick=()=>document.querySelector(".nav").classList.toggle("open");
document.getElementById("year").textContent=new Date().getFullYear();
document.getElementById("ticker").innerHTML=`<div class="container ticker-inner">${DEMO_STOCKS.slice(0,6).map(s=>`<span>${s.symbol} <b>₹${s.price}</b> <i class="${s.change>=0?"up":"down"}">${s.change>=0?"+":""}${s.change}%</i></span>`).join("")}</div>`;
window.addEventListener("hashchange",route); route();
